Parameters:
  EnvName:
    Description: An Environment name that will be prefixed to resources
    Type: String

Resources:
  IAMRole:
    Type: "AWS::IAM::Role"
    Properties:
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/AmazonS3FullAccess"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - "ec2.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Path: "/"
    
  IAMIP:
    Type: "AWS::IAM::InstanceProfile"
    Properties:
      Path: "/"
      Roles:
        - Ref: "IAMRole"

Outputs:
  IAMRole:
    Description: "Allow EC2 instances to manage Web App S3"
    Value: !Ref IAMIP
    Export:
      Name: !Sub ${EnvName}-IAM-NAME
